name: 'dbt_transactions'
version: '1.0.0'
config-version: 2

profile: 'dbt_transactions'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_transactions:
    marts:
      +materialized: table

seeds:
  dbt_transactions:
    +tags: ['business']
